//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationBase
    {
        public int ApplicationID { get; set; }
        public int UserID { get; set; }
        public string CurrentEmployer { get; set; }
        public Nullable<int> CurrentEmployerTime { get; set; }
        public Nullable<float> CurrentEmployerPhone { get; set; }
        public string FormerEmployer { get; set; }
        public Nullable<int> FormerEmployerTime { get; set; }
        public Nullable<float> FormerEmployerPhone { get; set; }
        public int AnnualIncome { get; set; }
        public int FamilyMembersInHome { get; set; }
        public int Dependents { get; set; }
        public int Pets { get; set; }
        public string PetType { get; set; }
        public string RelationshipStatus { get; set; }
        public string ApplicationStreetAddr { get; set; }
        public string ApplicationCity { get; set; }
        public string ApplicationStateAbbr { get; set; }
        public int ApplicationZip { get; set; }
        public string ApplicationCounty { get; set; }
    
        public virtual UserBase UserBase { get; set; }
    }
}
