//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInformation
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string FormerFirstName { get; set; }
        public string FormerLastName { get; set; }
        public string PreferredFirstName { get; set; }
        public string CurrentStreetAddr { get; set; }
        public string CurrentCity { get; set; }
        public string CurrentStateAbbr { get; set; }
        public Nullable<int> CurrentZip { get; set; }
        public string CurrentCountry { get; set; }
        public string CurrentCounty { get; set; }
        public Nullable<int> ResidencyYR { get; set; }
        public string FormerStreetAddr { get; set; }
        public string FormerCity { get; set; }
        public string FormerStateAbbr { get; set; }
        public Nullable<int> FormerZip { get; set; }
        public string FormerCountry { get; set; }
        public string FormerCounty { get; set; }
        public Nullable<int> CellPhone { get; set; }
        public Nullable<int> WorkPhone { get; set; }
        public string Email { get; set; }
        public string MailingStreetAddr { get; set; }
        public string MailingCity { get; set; }
        public string MailingStateAbbr { get; set; }
        public Nullable<int> MailingZip { get; set; }
        public string MailingCountry { get; set; }
        public string MailingCounty { get; set; }
    
        public virtual UserBase UserBase { get; set; }
        public virtual UserBase UserBase1 { get; set; }
    }
}
